import "./globals.css";
import { Work_Sans } from "next/font/google";
import NavBar from "@/components/navBar/NavBar";

const work_Sans = Work_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={work_Sans.className}>
      <body className="text-darkGray">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
